version : '3'

services:
    web-server:
        build: ./web-server
        image: web-server_nodeapp
        container_name: web-server
        ports:
            - "3000:3000"
        volumes:
            - "./web-server/:/code/web-server"
        links: 
            - "api-gateway:api-gateway"
        environment:
            - APPID=1111
    api-gateway:
        build: ./api-gateway
        image: api-gateway_nodeapp
        container_name: api-gateway
        ports:
            - "4000:4000"
        volumes: 
            - "./api-gateway/:/code/api-gateway"
        links: 
            - "user-service:user-service"
            - "inventory-service:inventory-service"
            - "purchasing-service:purchasing-service"
        environment:
            - APPID=2222
    user-service:
        build: ./user-service
        image: user-service_nodeapp
        container_name: user-service
        ports:
            - "5000:5000"
        volumes: 
            - "./user-service/:/code/user-service"
            # - "./user-service/:/code/node_modules"
        environment:
            - APPID=3333
    inventory-service:
        build: ./inventory-service
        image: inventory-service_nodeapp
        container_name: inventory-service
        ports:
            - "6500:6500"
        volumes: 
            - "./inventory-service/:/code/inventory-service"
        environment:
                    - APPID=3333
    purchasing-service:
        build: ./purchasing-service
        image: purchasing-service_nodeapp
        container_name: purchasing-service
        ports:
            - "7000:7000"
        volumes: 
            - "./purchasing-service/:/code/purchasing-service"
        environment:
            - APPID=5555
    log-service:
        build: ./log-service
        image: log-service_nodeapp
        container_name: log-service
        ports:
            - "8000:8000"
        volumes: 
            - "./log-service/:/code/log-service"
        links: 
            - "web-server:web-server"
            - "user-service:user-service"
            - "inventory-service:inventory-service"
            - "purchasing-service:purchasing-service"
        environment:
            - APPID=6666